FROM node:12.22.12
LABEL maintainer=pablo@ppamo.cl
EXPOSE 4200
RUN apt update && apt -y upgrade && \
	printf "alias c='cd'; alias l='ls -plh'; alias la='ls -plah'" >> $HOME/.bashrc
WORKDIR /app
VOLUME app
RUN npm install -g @angular/cli bootstrap
